[package]
name = "list-management"
version = "0.1.0"
edition = "2021"

[dependencies]
currency_rs = "1.3.0"
chrono = "0.4.38"

diesel = { version = "2.2.2", features = ["sqlite", "chrono"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15"
